name: flutter_getx_mvc_guide
description: "Flutter GetX MVC Architecture Guide"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  http: ^1.2.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/animation/
  - assets/images/raster/
  - assets/images/vector/
  - assets/icons/vector/
  - assets/icons/vector/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
